<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="style.css" />
<title>AT&T Website Solutions</title>
</head>

<body>
<div id="main">
	<div id="content">
		<div id="welcom_img"><img src="img/welcome.jpg" alt="Welcome to the future site of" title="Welcome to the future site of"  /></div>
		<h1><?php echo $_SERVER['HTTP_HOST'] ?></h1>
		<h2>This site is under construction or otherwise unavailable. Please check back later.<br />
				<br />
			Hosting is provided by AT&amp;T Web Solutions<sup>SM</sup></h2>
		<div id="gadgets">&nbsp;</div>
		<p><b>NOTE:</b> AT&amp;T does not own this domain name. To learn about hosting products and services provided by AT&amp;T, please visit us at <a href="http://webhosting.att.com" target="_blank">http://webhosting.att.com</a>.</p>
	</div>
	<div id="footer">
		<div id="att_img">&nbsp;</div>
		<div id="footer_content">
			<p><span class="blue">&copy; 2012 AT&amp;T Intellectual Property.</span> All rights reserved. AT&amp;T products and services are provided or offered by subsidiaries and affiliates of AT&amp;T Inc. under the AT&amp;T brand and not by AT&amp;T Inc. AT&amp;T, AT&amp;T logo and all other AT&amp;T marks contained herein are trademarks of AT&amp;T Intellectual Property and/or AT&amp;T affiliated companies. All other trademarks are the property of their owners. This document is not an offer, commitment, representation or warranty by AT&amp;T and is subject to change.</p>
		</div>
	</div>
</div>
</body>
</html>
